config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :rooms
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  # has_many: concerts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @rooms = Room.all
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
skip_before_action :authenticate_user!

    def index
      @rooms = Room.all
      @room = Room.new
    end

    def show
      @room = Room.find(params[:id])
    end

    def new
      @room = Room.new
    end

    def edit
      @room = Room.find(params[:id])
    end

    def update
    @room = Room.find(params[:id])
    @room.update(room_params)
    redirect_to room_path(@room)
    end

    def create
      @room = Room.new(room_params)
      @room.save
    end

    def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to root_path
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :adress, :website, :capacity)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scraping</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class= sidebar></div>

<div class="banner">
  <div class="container">

    <h1>Find the best <strong>concerts</strong> in <strong>Paris</strong>!</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>


<div class="room">
<ul>
  <% @rooms.each do |room| %>
    <li><%= room.name %> <%= link_to 'See concerts', room_path(room) %></li>
  <% end %>
</ul>


<%= link_to 'Add a room', new_room_path %>
</div>

app/views/rooms/edit.html.erb
<%= simple_form_for @room do |f| %>
      <%= f.input :name %>
      <%= f.input :adress %>
      <%= f.input :website %>
      <%= f.input :capacity %>
      <%= f.button :submit %>
<% end %>

app/views/rooms/new.html.erb
<h2>Add a Room</h2>
      <h2>Create your Food Truck</h2>
      <%= simple_form_for @room do |f| %>
      <%= f.input :name %>
      <%= f.input :adress %>
      <%= f.input :website %>
      <%= f.input :capacity %>
      <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<li><%= @room.name %></li>
<li><%= @room.adress %></li>
<li><%= @room.website %></li>
<li><%= @room.capacity %></li>
<li><%= link_to 'Edit', edit_room_path %></li>
<%= link_to "Delete #{@room.name}",
            room_path(@room),
            method: :delete,
            data: { confirm: "Are you sure?" } %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="grille">
    <div class="grille-item"></div>
    <div class="grille-item"></div>
    <div class="grille-item"></div>
    <div class="grille-item"></div>
    <div class="grille-item"></div>
    <div class="grille-item"></div>
    <div class="grille-item"></div>
    <div id="title">
      <h2>Concerts</h2>
    </div>
    <div class="grille-item"></div>
    <div class="grille-item"></div>
    <div class="grille-item"></div>
    <div class="grille-item"></div>
    <div class="grille-item"></div>
    <div class="grille-item">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
      </div>
    </div>



</div>

app/views/shared/test.html.erb
test.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>